### ISSUE TITLE
servers.json is not such a file to open

### ISSUE THREAD

**Issue by Pinont** [evilguy50/bdsx-serverTransfer#1]
Error: ENOENT: no such file or directory, open './servers.json'
   at openSync (fs.js:451:3)
   at readFileSync (fs.js:351:3)
   at Anonymous function (D:\MCBE Server\Main\plugins\bdsx-serverTransfer-main\transfer.ts:16:5)
   at CustomCommandImpl.prototype.execute (D:\MCBE Server\Main\bdsx\command.ts:113:21)
   at Anonymous function (D:\MCBE Server\Main\bdsx\command.ts:167:13)
   at Anonymous function (Function code:9:1)
   at Anonymous function (Function code:10:1)
   at executeCommand (D:\MCBE Server\Main\bdsx\command.ts:28:13)
   at Anonymous function (Function code:10:1)

**Comment by evilguy50** [comment]
solved by following the readme file.
"after installing make sure to move servers.json into the bedrock_server directory before starting bdsx."
